export const LOADING_MOVIES = 'LOADING_MOVIES';
export type LOADING_MOVIES = typeof LOADING_MOVIES;

export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export type LOAD_MOVIES_SUCCESS = typeof LOAD_MOVIES_SUCCESS;

export const LOADING_MOVIES_ERROR = 'LOADING_MOVIES_ERROR';
export type LOADING_MOVIES_ERROR = typeof LOADING_MOVIES_ERROR;

export const SELECT_MOVIE = 'SELECT_MOVIE';
export type SELECT_MOVIE = typeof SELECT_MOVIE;

export const ADD_MOVIE = 'ADD_MOVIE';
export type ADD_MOVIE = typeof ADD_MOVIE;

export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export type UPDATE_MOVIE = typeof UPDATE_MOVIE;

export const DELETE_MOVIE = 'DELETE_MOVIE';
export type DELETE_MOVIE = typeof DELETE_MOVIE;

export const FILTER_BY_RELEASE_DATE_AND_RATING =
  'FILTER_BY_RELEASE_DATE_AND_RATING';
export type FILTER_BY_RELEASE_DATE_AND_RATING = typeof FILTER_BY_RELEASE_DATE_AND_RATING;

export const SORT_BY_GENRE = 'SORT_BY_GENRE';
export type SORT_BY_GENRE = typeof SORT_BY_GENRE;
