export enum ACTIONS {
  LOADING_MOVIES = 'LOADING_MOVIES',
  LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS',
  LOADING_MOVIES_ERROR = 'LOADING_MOVIES_ERROR',
  ADD_MOVIE = 'ADD_MOVIE',
  UPDATE_MOVIE = 'UPDATE_MOVIE',
  DELETE_MOVIE = 'DELETE_MOVIE',
  SELECT_MOVIE = 'SELECT_MOVIE',
  FILTER_BY_RELEASE_DATE_AND_RATING = 'FILTER_BY_RELEASE_DATE_AND_RATING',
  SORT_BY_GENRE = 'SORT_BY_GENRE',
}
